apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-pvc
  namespace: testingrizwan
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-pvc
  template:
    metadata:
      labels:
        app: nginx-pvc
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: webdata
          mountPath: /usr/share/nginx/html
      volumes:
      - name: webdata
        persistentVolumeClaim:
          claimName: my-pvc
